# Generated by Django 5.0.7 on 2024-09-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='accounts.area'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'city', 'parent')},
        ),
    ]
