# Generated by Django 5.1.1 on 2024-10-08 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='technicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
