# Generated by Django 5.1.1 on 2024-10-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_team_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
