# Generated by Django 5.0.7 on 2024-07-31 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cdr3cx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounts.company'),
        ),
    ]
