# Generated by Django 5.0.7 on 2024-08-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extension_email'),
        ('cdr3cx', '0002_callrecord_company_routingrule_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Pattern for matching callee numbers, e.g., +1, 059', max_length=20)),
                ('call_type', models.CharField(choices=[('mobile', 'Mobile'), ('national', 'National'), ('international', 'International'), ('local', 'Local')], max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description of the pattern', max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_patterns', to='accounts.company')),
            ],
        ),
    ]
