# Generated by Django 5.0.7 on 2024-08-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0003_callpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='call_category',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('national', 'National'), ('international', 'International'), ('local', 'Local')], max_length=20, null=True),
        ),
    ]
