# Generated by Django 5.0.7 on 2024-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0004_callrecord_call_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpattern',
            name='rate_per_min',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per minute in SAR', max_digits=5),
        ),
    ]
