# Generated by Django 5.0.7 on 2024-09-07 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extension_email'),
        ('cdr3cx', '0006_callrecord_call_rate_callrecord_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='accounts.extension')),
                ('quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdr3cx.quota')),
            ],
        ),
    ]
