# Generated by Django 5.0.7 on 2024-09-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0007_quota_userquota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutingRule',
        ),
    ]
