# Generated by Django 5.0.7 on 2024-09-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0008_delete_routingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpattern',
            name='call_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('national', 'National'), ('international', 'International'), ('local', 'Local'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='call_category',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('national', 'National'), ('international', 'International'), ('local', 'Local'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
    ]
