# Generated by Django 5.0.7 on 2024-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0009_alter_callpattern_call_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquota',
            old_name='remaining_balance',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='userquota',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
