# Generated by Django 5.0.7 on 2024-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0010_rename_remaining_balance_userquota_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='monthly', max_length=10, null=True),
        ),
    ]
