# Generated by Django 5.0.7 on 2024-10-05 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingslot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workingslot',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 minutes'), (datetime.timedelta(seconds=3600), '1 hour'), (None, 'Custom')]),
        ),
    ]
