# Generated by Django 5.0.7 on 2024-10-05 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_workingslot_date_alter_workingslot_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workingslot',
            name='duration',
        ),
        migrations.AddField(
            model_name='workingslot',
            name='gap_between_slots',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Optional gap between slots.'),
        ),
    ]
