# Generated by Django 5.0.7 on 2024-08-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='listening_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
