# Generated by Django 5.0.7 on 2024-08-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ['company', 'extension']},
        ),
        migrations.AlterField(
            model_name='extension',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together={('extension', 'company')},
        ),
    ]
