# Generated by Django 5.1.1 on 2024-10-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['slot__date', 'slot__start_time']},
        ),
    ]
