# Generated by Django 5.1.1 on 2024-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_first_name_customuser_last_name'),
        ('crmapp', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='accounts.service'),
        ),
    ]
