# Generated by Django 5.1.1 on 2024-10-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_technician_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crmapp.technician'),
        ),
    ]
