# Generated by Django 5.1.1 on 2024-10-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_appointment'),
        ('crmapp', '0004_appointment_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(blank=True, to='accounts.service'),
        ),
    ]
