# Generated by Django 5.1.1 on 2024-10-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_appointment_materials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technicianschedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='technicianschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='end_date_after_start_date'),
        ),
    ]
