# Generated by Django 5.1.1 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_appointment'),
        ('crmapp', '0008_alter_technicianschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='crmapp.material'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='accounts.service'),
        ),
    ]
